name: test_release

on:
  release:
    types: [created]
  workflow_dispatch:
    
jobs:
  #testing:
  #  uses: ./.github/workflows/testing.yml
  publish:
    #needs: testing
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Upload to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: "https://test.pypi.org/legacy/"
          password: ${{ secrets.PYPI_TEST_FGC }}
      #- name: Upload to PyPI
      #  env:
      #    TWINE_USERNAME: __token__
      #    TWINE_PASSWORD: ${{ secrets.PYPI_TEST_FGC }}
      #  run: | 
      #    python -m pip install --upgrade pip
      #    pip install twine
      #    twine upload --repository-url=https://test.pypi.org/legacy/ dist/*
