name: testing

on: 
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
  
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        
    steps:
    - name: Checkout Repository 
      uses: actions/checkout@v3
    #- name: Set up Python ${{ matrix.python-version }}
    #  uses: actions/setup-python@v4
    #  with:
    #    python-version: ${{ matrix.python-version }}
    #- name: Add conda to system path
    #  run: |
    #    # $CONDA is an environment variable pointing to the root of the miniconda directory
    #    echo $CONDA/bin >> $GITHUB_PATH
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: anaconda, conda-forge
    - run: conda --version
    - run: which python
    - name: Install dependencies
      run: |
        conda install -c conda-forge rust
        python -m pip install --upgrade pip
        pip install pytest
        pip install -e .
    - name: Test with pytest
      run: pytest
